name: flutter_checkbox_dialog
description: Package for integrating "CheckboxListTile" into "AlertDialog".
version: 0.0.1
homepage: https://github.com/morio77/flutter_checkbox_dialog

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_checkbox_dialog
        pluginClass: FlutterCheckboxDialogPlugin
      ios:
        pluginClass: FlutterCheckboxDialogPlugin
